<?php

use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */
$this->layout('error/layout');
?>
<!-- start: PAGE HEADER -->
<div class="row">
    <div class="col-sm-12">
        <!-- start: PAGE TITLE & BREADCRUMB -->
        <ol class="breadcrumb">
            <li>
                <i class="clip-attachment-2"></i>
                <a href="#">
                    Utility
                </a>
            </li>
            <li class="active">
                Error 500
            </li>
        </ol>
        <!-- end: PAGE TITLE & BREADCRUMB -->
    </div>`
</div>
<!-- end: PAGE HEADER -->
<!-- start: PAGE CONTENT -->
<div class="row">
    <!-- start: 500 -->
    <div class="col-sm-12 page-error">
        <div class="error-number bricky">
            500
        </div>
        <div class="error-details col-sm-6 col-sm-offset-3">
            <h3>Oops! You are stuck at 500</h3>
            <p><?= $message; ?></p>
        </div>
    </div>
    <!-- end: 500 -->
</div>

<div class="row">
    <div class="col-xs-12">
    <?php if (! empty($this->display_exceptions)) : ?>
        <?php if (isset($this->exception) && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
            <hr/>

            <h2>Additional information:</h2>
            <h3><?= get_class($this->exception) ?></h3>
            <dl>
                <dt>File:</dt>
                <dd>
                    <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
                </dd>
                <dt>Message:</dt>
                <dd>
                    <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
                </dd>
                <dt>Stack trace:</dt>
                <dd>
                    <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                </dd>
            </dl>

            <?php
            $ex = $this->exception->getPrevious();
            if ($ex) : ?>
                <hr/>

                <h2>Previous exceptions:</h2>
                <ul class="list-unstyled">
                    <?php $icount = 0 ?>
                    <?php while ($ex) : ?>
                        <li>
                            <h3><?= get_class($ex) ?></h3>
                            <dl>
                                <dt>File:</dt>
                                <dd>
                                    <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
                                </dd>
                                <dt>Message:</dt>
                                <dd>
                                    <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
                                </dd>
                                <dt>Stack trace:</dt>
                                <dd>
                                    <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
                                </dd>
                            </dl>
                        </li>
                        <?php
                        $ex = $ex->getPrevious();
                        if (++$icount >= 50) {
                            echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
                            break;
                        }
                        ?>
                    <?php endwhile ?>
                </ul>
            <?php endif ?>
        <?php else : ?>
            <h3>No Exception available</h3>
        <?php endif ?>
    <?php endif ?>
    </div>
</div>
<!-- end: PAGE CONTENT-->
