<?php
/** @var Laminas\View\Renderer\PhpRenderer $this */

use Laminas\View\Renderer\PhpRenderer;

/** @var $this PhpRenderer */
echo $this->doctype();
?>
<!--[if IE 8]><html class="ie8 no-js" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9 no-js" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta charset="utf-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <?= $this->headTitle('K3S Dev Tools')->setAutoEscape(false) ?>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <?= $this->headMeta()->appendName('viewPort', 'width=device-width, initial-scale=1.0, shrink-to-fit=no') ?>
    <title>K3S Dev Tools </title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/theme/star-admin2-free-admin-template-main/template/vendors/feather/feather.css">
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/vendors/typicons/typicons.css">
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/vendors/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="theme/star-admin2-free-admin-template-main/template/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="theme/star-admin2-free-admin-template-main/template/images/favicon.png" />


    <?php
    echo $this->headLink();
    ?>


</head>
<body class="navigation-small">
    <div class="container-scroller">

        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
                <div class="me-3">
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
                        <span class="icon-menu"></span>
                    </button>
                </div>
                <div>
                    <a class="navbar-brand brand-logo" href="index.html">
                        <img src="logo.png" alt="logo" />
                    </a>
                    <a class="navbar-brand brand-logo-mini" href="index.html">
                        <img src="logo.png" alt="logo" />
                    </a>
                </div>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item"><a href="/generate-sql-file-for-github-issue" class="nav-link active" aria-current="page">API Build</a></li>
                    <li class="nav-item"><a href="/generate-sql-insert" class="nav-link">Generate SQL Insert</a></li>
                    <li class="nav-item"><a href="/generate-table-data-gateway-service-program" class="nav-link">Generate TDG Service Program</a></li>
                    <li class="nav-item"><a href="/generate-new-api" class="nav-link">Generate new API</a></li>
                    <li class="nav-item"><a href="/move-gutter-comments-to-end-of-line" class="nav-link">Move Gutter Comments to EOL</a></li>
                    <li class="nav-item"><a href="/helpful-links" class="nav-link">Helpful Links</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Other tools</a></li>
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <?= $this->content; ?>
                    </div>
                </div>
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- plugins:js -->
    <script src="theme/star-admin2-free-admin-template-main/template/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="theme/star-admin2-free-admin-template-main/template/vendors/chart.js/Chart.min.js"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/vendors/progressbar.js/progressbar.min.js"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="theme/star-admin2-free-admin-template-main/template/js/off-canvas.js"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/js/hoverable-collapse.js"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/js/template.js"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/js/settings.js"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="theme/star-admin2-free-admin-template-main/template/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/js/dashboard.js"></script>
    <script src="theme/star-admin2-free-admin-template-main/template/js/Chart.roundedBarCharts.js"></script>
    <!-- End custom js for this page-->
    <?php
    echo $this->inlineScript()
    ?>
</body>
</html>
