<?php
/** @var $apiRootName string */
/** @var $author string */
/** @var $description string */
/** @var $githubIssueNumber string */
/** @var $currentDate DateTimeInterface */
?>

/*******************************************************************/
/*                                                                 */
/*   K3S-Replenish (R) - Inventory REPLENISHment System            */
/*   Copyright (C) 1996-<?= (new DateTime('now'))->format('Y') ?> by King III Solutions, Inc.           */
/*   Program property of King III Solutions, Inc.                  */
/*   All rights reserved.                                          */
/*   K3S_Replenish (R) is a Registered Trade Mark of               */
/*   King III Solutions Inc.                                       */
/*                                                                 */
/*******************************************************************/
/*                                                                 */
/*         Name: AC_<?= $apiRootName ?>                                        */
/*         Type: CL Program                                        */
/*         Auth: <?= $author ?>                                      */
/*         Desc: Web - <?= $description ?>             */
/*                                                                 */
/*******************************************************************/
/*                                                                 */
/*   Modifications:                                                */
/*   Change ID  Change Date Change Description                     */
/*   ---------  ----------  ---------------------------------------*/
/*     <?= $githubIssueNumber ?>    <?= $currentDate->format('Y-m-d') ?>  Initially written.                     */
/*                                                                 */
/*******************************************************************/
/*                                                                 */
/*******************************************************************/

PGM        PARM(&K3SOBJ &COMP &COMPCOD &USER &ERRORS &ERRMSG +
             &ERRFIELD)

/*******************************************************************/
/*   Copyrights                                                    */
/*******************************************************************/

COPYRIGHT  TEXT('(C) Copyright 1996 - 2016 King III +
Solutions, Inc.  Rel 6.01 +
2016-01-01       Program Property of King +
III Solutions, Inc. All rights +
reserved              K3S_Replenish (R) +
is a Registered Trade Mark of King III +
Solutions Inc.')

/*******************************************************************/
/*------------------------------ K3S parameters -------------------*/
/*******************************************************************/

/*      K3S Object library                                           */
DCL        VAR(&K3SOBJ) TYPE(*CHAR) LEN(10)

/*      Company                                                      */
DCL        VAR(&COMP) TYPE(*CHAR) LEN(1)

/*      3 letter Company Code                                        */
DCL        VAR(&COMPCOD) TYPE(*CHAR) LEN(3)

/*      User                                                         */
DCL        VAR(&USER) TYPE(*CHAR) LEN(10)

/*      Error                                                        */
DCL        VAR(&ERRORS) TYPE(*CHAR) LEN(1)

/*      Error message                                                */
DCL        VAR(&ERRMSG) TYPE(*CHAR) LEN(100)

/*      Error field                                                  */
DCL        VAR(&ERRFIELD) TYPE(*CHAR) LEN(20)

/*******************************************************************/
/*------------------------------ Normal Process -------------------*/
/*******************************************************************/

ADDLIBLE   LIB(&K3SOBJ)
MONMSG     MSGID(CPF0000)

/*******************************************************************/
/*      Call program to process mass field update batch            */
/*******************************************************************/
CALL       PGM(AR_<?= $apiRootName ?>) PARM(&COMP &COMPCOD &USER +
&ERRORS &ERRMSG &ERRFIELD)

K3S_FINAL:  ENDPGM

