<?php
/** @var $apiRootName string */
/** @var $author string */
/** @var $description string */
/** @var $githubIssueNumber string */
/** @var $currentDate DateTimeInterface */
/** @var $parameters array[] */
?>

/*******************************************************************/
/*                                                                 */
/*   K3S-Replenish (R) - Inventory REPLENISHment System            */
/*   Copyright (C) 1996-<?= (new DateTime('now'))->format('Y') ?> by King III Solutions, Inc.           */
/*   Program property of King III Solutions, Inc.                  */
/*   All rights reserved.                                          */
/*   K3S_Replenish (R) is a Registered Trade Mark of               */
/*   King III Solutions Inc.                                       */
/*                                                                 */
/*******************************************************************/
/*                                                                 */
/*         Name: TS_<?= $apiRootName ?>                                        */
/*         Type: CL Program                                        */
/*         Auth: <?= $author ?>                                      */
/*         Desc: Web - <?= $description ?>             */
/*                                                                 */
/*******************************************************************/
/*                                                                 */
/*   Modifications:                                                */
/*   Change ID  Change Date Change Description                     */
/*   ---------  ----------  ---------------------------------------*/
/*     <?= $githubIssueNumber ?>    <?= $currentDate->format('Y-m-d') ?>  Initially written.                     */
/*                                                                 */
/*******************************************************************/
/*                                                                 */
/*******************************************************************/

PGM        PARM(<?php
$count = 0;
foreach ($parameters as $parameter) {
    if (($count > 0) && ($count % 5 == 0)) {
        echo "+\n                ";
    }
    echo "&" . strtoupper($parameter['parameterName']) . ' ';
    $count++;
} ?>)

/*******************************************************************/
/*   Copyrights                                                    */
/*******************************************************************/

COPYRIGHT  TEXT('(C) Copyright 1996 - 2016 King III +
Solutions, Inc.  Rel 6.01 +
2016-01-01       Program Property of King +
III Solutions, Inc. All rights +
reserved              K3S_Replenish (R) +
is a Registered Trade Mark of King III +
Solutions Inc.')

/*******************************************************************/
/*------------------------------ K3S parameters -------------------*/
/*******************************************************************/

<?php
$count = 0;
foreach ($parameters as $parameter) {
    echo "/*      ";
    echo $parameter['description'];
    $spaces = "                                                             ";
    echo substr($spaces, strlen($parameter['description']), (61-strlen($parameter['description'])));
    echo "*/" . "\n";  // 61 chars between asterisks
    echo "DCL      ";
    echo "VAR(&" . strtoupper($parameter['parameterName']) . ") TYPE(";
    if (str_contains($parameter['dataType'], 'Char')) {
        echo "*CHAR";
    } else {
        echo "*DEC";
    }
    echo ") ";

    echo "LEN(";
    echo $parameter['length'] . ' ' . $parameter['precision'];
    echo ") VALUE()";
    echo "\n\n";

    $count++;
} ?>

/*******************************************************************/
/*------------------------------ Normal Process -------------------*/
/*******************************************************************/

ADDLIBLE   LIB(&K3SOBJ)
MONMSG     MSGID(CPF0000)

/*******************************************************************/
/*      Call program to process mass field update batch            */
/*******************************************************************/
CALL       PGM(AC_<?= $apiRootName ?>) PARM(<?php
$count = 0;
foreach ($parameters as $parameter) {
    if ($parameter['parameterName'] === 'k3sobj') {
        continue;
    }
    if (($count > 0) && ($count % 5 == 0)) {
        echo "+\n                ";
    }
    echo "&" . strtoupper($parameter['parameterName']) . ' ';
    $count++;
} ?>)

K3S_FINAL:  ENDPGM

